name: build container image for container-object-storage-interface-csi-adapte

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *' # every day at midnight

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout kubernetes-sigs/container-object-storage-interface-csi-adapter
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/container-object-storage-interface-csi-adapter

    - name: Build with Gradle
      run: |
        ls -al
        pwd

    # - name: Login to Quay.io
    #   uses: docker/login-action@v1
    #   with:
    #     logout: true
    #     registry: quay.io
    #     username: ${{ secrets.QUAY_USERNAME }}
    #     password: ${{ secrets.QUAY_TOKEN }}
